stages:

  collect:
    cmd: python src/pipeline/collect.py --output data/raw/iris_raw.csv
    deps:
      - src/pipeline/collect.py
    outs:
      - data/raw/iris_raw.csv

  preprocess:
    cmd: python src/pipeline/preprocess.py --input data/raw/iris_raw.csv --output data/processed/iris_preprocessed.csv
    deps:
      - src/pipeline/preprocess.py
      - data/raw/iris_raw.csv
    outs:
      - data/processed/iris_preprocessed.csv

  features:
    cmd: python src/pipeline/features.py --input data/processed/iris_preprocessed.csv --output data/processed/iris_features.csv
    deps:
      - src/pipeline/features.py
      - data/processed/iris_preprocessed.csv
    outs:
      - data/processed/iris_features.csv

  validate:
    cmd: python src/pipeline/validate.py --input data/processed/iris_features.csv
    deps:
      - src/pipeline/validate.py
      - data/processed/iris_features.csv